- name: Install Opera browser
  tags: &tags_browser [ 'browser', 'opera' ]
  become: true
  when: '"opera-stable" not in ansible_facts.packages'
  block:  
    - name: Download Opera gpg key
      get_url:
        url: https://deb.opera.com/archive.key
        dest: /usr/share/keyrings/opera-browser.gpg_armored

    - name: De-Armor Opera gpg key
      shell: gpg --dearmor < /usr/share/keyrings/opera-browser.gpg_armored > /usr/share/keyrings/opera-browser.gpg
      no_log: true
      args:
        creates: /usr/share/keyrings/opera-browser.gpg

    - name: Add Opera repository to APT sources list
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/opera-browser.gpg] https://deb.opera.com/opera-stable/ stable non-free"
        state: present
        filename: opera-stable

    - name: Install Opera
      apt:
        update_cache: yes
        name: opera-stable
      
