- name: Set up .ssh key
  tags: &tags_ssh [ 'install', 'core', 'dotfiles', 'ssh' ]
  vars:
    source_key: .ssh/key
    dest_key: "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh/key"
  block:
    - name: Create .ssh dir
      ansible.builtin.file:
        path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh"
        state: directory
        mode: '0755'
        
    - name: Check if .ssh dir exists
      stat:
        path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh"
      register: ssh_dir

    - name: Install ssh key
      copy:
        src: "{{ source_key }}"
        dest: "{{ dest_key }}"
        mode: 0600
      when: ssh_dir.state.exists and ssh_dir.state.isdir

    - name: Install ssh key public
      copy:
        src: "{{ source_key }}.pub"
        dest: "{{ dest_key }}.pub"
        mode: 0644
      when: ssh_dir.state.exists and ssh_dir.state.isdir
      
    - name: Check if key.pub exists
      stat:
        path: "{{ dest_key }}.pub"
      register: ssh_pub

    - name: Set authorized key taken from file
      vars:
        key: "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh/key.pub"
      ansible.posix.authorized_key:
        user: "{{ lookup('ansible.builtin.env', 'USER') }}"
        state: present
        key: "{{ lookup('file', key) }}"
      with_fileglob:
        - "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh/*.pub"
      when: ssh_pub.state.exists
