- name: Set up .ssh key
  tags: &tags_ssh [ 'install', 'core', 'dotfiles', 'ssh' ]
  block:
    - name: Create .ssh dir
      ansible.builtin.file:
      path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh"
      state: directory
      mode: '0755'
  
    - name: Install ssh key
      copy:
        src: "{{ source_key }}"
        dest: "{{ dest_key }}"
        mode: 0600
        
    - name: Install ssh key public
      copy:
        src: "{{ source_key }}.pub"
        dest: "{{ dest_key }}.pub"
        mode: 0644
        
    - name: Set authorized key took from file
      authorized_key:
        user: "{{ lookup('env', 'USER') }}"
        state: present
        key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
      with_fileglob:
        - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
